### ISSUE TITLE
Wrong line in get_info.py

### ISSUE THREAD

**Issue by Stucchi2000** [Stucchi2000/bookmasters-LSPD#1]
Hi @Friccoz27,

I see that in the "get_info.py" file you uploaded you evoke the suggestion function which still needs to be developed. 

If you let me I will pull the commit and modify it and after that, I will merge the code into my "class_bookrecords.py" file

Thank you,
Stefano

**Comment by Friccoz27** [comment]
Thank you for fixing this @Stucchi2000 .

**Comment by Stucchi2000** [comment]
I did the modifications, I now merge the function into my branch
